### ISSUE TITLE
Local file dependencies don't work when cloning

### ISSUE THREAD

**Issue by uncovery** [PolyhedralDev/Terra#1]
See this: https://github.com/PolyhedralDev/Terra/blob/669cb1b53e85003e4d36d70d24c17385c798b19e/pom.xml#L65
and this: https://github.com/PolyhedralDev/Terra/blob/669cb1b53e85003e4d36d70d24c17385c798b19e/pom.xml#L78

Both these local repositories in the config are becoming invalid when other people clone the repository. It would be helpful if you would either 

1.  state in the readme.md where those can be downloaded to the user's local repo and tell them where to change the pom.xml or 

2. create a public repository where they can be accessed, change the POM accordingly or 

3. include the files in this repository and make the path relative to those files instead.

if you help me with 1., I can make a pull request for 3.

**Comment by dfsek** [comment]
So sorry about this, I totally forgot to have those relative. This has been fixed.
