### ISSUE TITLE
Incompatibility with OptiFabric

### ISSUE THREAD

**Issue by devKurai** [PolyhedralDev/Terra#100]
When taking terra out of the mods folder, Optifine works completely fine as normal, Once in, it fails to produce the settings tab or anything to do with Optifine/Optifabric.

https://www.curseforge.com/minecraft/mc-mods/optifabric

One of the logs when starting game with both mods installed, if it helps
https://pastebin.com/zwgsWR9n

![image](https://user-images.githubusercontent.com/81210104/112095815-ebd1c980-8be8-11eb-84e7-365cf5238212.png)

**Comment by dfsek** [comment]
OptiFine is gross and bad. Support for it will not be considered. It should not be used with any Fabric mods. Use Sodium+Lithium+Starlight for performance, and the plethora of other mods for additional features.

Useful list: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by devKurai** [comment]
I just want my shaders :(

**Comment by dfsek** [comment]
https://github.com/IrisShaders/Iris

**Comment by solonovamax** [comment]
We should still try and get at least _some_ functionality for optifabric. (Because that's what I was using for shaders in the replaymod showcase I made)
But it'd be low priority
