### ISSUE TITLE
Feature request: add a loot generate event for chests

### ISSUE THREAD

**Issue by sachingorkar102** [PolyhedralDev/Terra#105]
Add a loot generate event for chests and other tile entities that generate with terra's custom structures just like one present in spigot api [LootGenerateEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/world/LootGenerateEvent.html)

**Comment by dfsek** [comment]
Implemented in 20c905aae458720fe2b87bd9f0b3af06779a1dab.

`com.dfsek.terra.api.event.events.world.generation.LootPopulateEvent`
