### ISSUE TITLE
(Fabric) Add modded structures to /te structure locate

### ISSUE THREAD

**Issue by xieve** [PolyhedralDev/Terra#114]
I'm currently using a few structure mods alongside Terra, which seem to work fine, however /locate is replaced with /te structure locate, which only supports vanilla and Terra structures. This means I can't easily locate any of the modded structures.

**Comment by solonovamax** [comment]
Well see, the problem is:
- Spigot APIs don't have any method of adding structures to the `/locate` command
-  the command will crash your server if you run it with a structure that doesn't exist (because mojang can't do a basic `if` check)

So, the *best* we could do is expose an API for it and allow other mods to integrate that. But you'd have to convince those mod authors to integrate it. (Also, Terra doesn't support locating vanilla structures. It only supports locating Terra structures, which we have copied from vanilla)

**Comment by xieve** [comment]
Hmm. I think this is different on Fabric, because I can see the auto-completion for /locate for different mods. Is there any way the vanilla locate could be wrapped with the correct `if` statement and then be blocked for the end user?

**Comment by solonovamax** [comment]
Yes, but we're a platform independent mod. We can't just change smth for fabric without doing it for all other impls.

**Comment by dfsek** [comment]
`/te structure locate` is for locating terra structures. We don't generate other mods' structures, so why should we include them in the command?

**Comment by solonovamax** [comment]
Also that

**Comment by xieve** [comment]
> `/te structure locate` is for locating terra structures. We don't generate other mods' structures, so why should we include them in the command?

Because this mod makes it impossible to use the vanilla command.

**Comment by dfsek** [comment]
Theres no reason to use the Vanilla command, because theres nothing that it would be able to locate. We completely throw out all Vanilla generation and substitute our own, completely custom, generation pipeline.

**Comment by xieve** [comment]
> Theres no reason to use the Vanilla command, because theres nothing that it would be able to locate. We completely throw out all Vanilla generation and substitute our own, completely custom, generation pipeline.

Okay, so maybe the error is on my side. Should modded structures just not be able to work with Terra installed, because of the complete substitution of the pipeline? I'm like 90% sure I have modded structures in my world right now that I could've located using the vanilla command.

**Comment by solonovamax** [comment]
> Should modded structures just not be able to work with Terra installed, because of the complete substitution of the pipeline?
Well, depending on how other mod authors do it, they _may_ work. But we have no control over it.
