### ISSUE TITLE
Fabric artifact not available on JitPack.io

### ISSUE THREAD

**Issue by xieve** [PolyhedralDev/Terra#122]
See e.g. the end of [this log](https://jitpack.io/com/github/PolyhedralDev/Terra/8a933609ee/build.log). I think the Fabric target is built, too, but for whatever reason, the artifact isn't listed as found and hence not available.

**Comment by dfsek** [comment]
Why are you trying to put our stuff on Jitpack? We have a Maven repository, why not just request we publish artifacts there, lol

I went ahead and did that, the repo URL is `https://repo.codemc.io/repository/maven-public/`
Fabric dependency would be:
```kotlin
implementation("com.dfsek.terra.fabric:fabric:5.1.2-BETA+7a703ad0")
```

**Comment by xieve** [comment]
Oof, I simply didn't know and didn't see it. Maybe put it in the readme? Thanks for the fix

**Comment by xieve** [comment]
I added `modImplementation 'com.dfsek.terra.fabric:fabric:5.1.2-BETA+7a703ad0'` to my build.gradle along with the maven repo. `./gradlew --info --refresh-dependencies` runs fine now, but the jar isn't actually listed in external dependencies
And it's missing all packages in com.dfsek.terra.fabric on compilation. I can also confirm that my setup works with the bukkit version (it appears in the IntelliJ external dependency list and is usable for imports): this is definitely an issue with the Fabric artifact specifically. Not sure if I should open another issue.

**Comment by dfsek** [comment]
Why are you using `modImplementation`... use `compileOnly`

**Comment by xieve** [comment]
> Why are you using `modImplementation`... use `compileOnly`

Same problem.

**Comment by xieve** [comment]
Here's my build.gradle for reference: https://github.com/xieve/terra-compat/blob/master/build.gradle#L36
