### ISSUE TITLE
Overworld mobs have severely reduced or nonexistent spawnrate using the default pack

### ISSUE THREAD

**Issue by tastespurple** [PolyhedralDev/Terra#129]
This issue occurs using the latest build of Terra as well as the latest version of Fabric API as of 4/14/2021. This issue has also occurred using some previous versions, but I am not exactly sure which versions without being asked to check. Essentially, most passive overworld mobs fail to spawn, or spawn at a much lower rate compared to vanilla. 

Here is a list of the overworld mobs that did not spawn (naturally) during my tests:

-horses/mules/donkeys/undead horses/skeleton horses
-llamas
-polar bears
-panda bears
-parrots
-bats
-bees
-wolves
-foxes
-ocelots/cats
-rabbits
-turtles
-mooshrooms
-ALL passive aquatic life
-iron golems? (I'm not sure if your villages are supposed to generate with them or not, but they are absent)

Here is a list of the overworld mobs that _did_ spawn (naturally) during my tests, in order of least to most rare:
-villagers (appear completely unaffected, and actually have a higher population than I would think for the number of buildings/beds in their villages)
-sheep
-pigs
-chickens
-cows

Important Notes:
-No hostile mobs seem affected, in any dimension, whatsoever. Except phantoms and possibly drowned. However, I wasn't able to test this extensively, as I never came across any woodland mansions, strongholds, nether fortresses (though blazes were encountered somehow), sea structures, or end cities. Some of them I did not look for; others I just never found in my hours of generating chunks.
-In the overworld: passive mobs do not spawn in darker biomes like jungles **(at all)** or some forests (hardly), generally only in planes or mountainsides, yet hostile mobs spawn quite a bit in those dark areas at all times and all areas during the night (except drowned, which don't seem to show up even when around bodies of water).
-In the nether: from what I could tell, all mobs that I would have expected to be there were there, and in regular or even larger than expected numbers.
-I used Carpet to inspect the mob spawning rates in the overworld. Everything seemed to be as expected, with passive mobs listed as being able to spawn in locations I tested, and having a 100% chance to do so, yet there seemed to only be listings for sheep, pigs, chickens, and cows that were output by the command. At the time, I was trying to change the spawning configuration to fix the issue, so I don't have the clearest memory of what I did and what the mod said in response, **but that could point to an issue with the weights and groups settings in the .json files, and all the Terra biomes might be using the default config, which only specifies those 4 (sheep, pig, chicken, cow) as being able to spawn, and at a rate lower than what one might expect in specifically configured biomes.**

That's it. Hopefully that's enough for you to go off of. I would definitely suggest using a tool like Carpet to poke around a bit more. It's possible this is just a configuration error and Minecraft doesn't realize it's supposed to be spawning fish in oceans, etc.

**Comment by dfsek** [comment]
I did a bit more testing, this is fixed in #133

**Comment by tastespurple** [comment]
I don't think this is fixed. I downloaded the latest build from modrinth and I'm only seeing ambient water mob spawns having improved. Land mobs still spawn in the way described in the original post.
