### ISSUE TITLE
Biome Specific Mobs Do Not Spawn

### ISSUE THREAD

**Issue by Hexcede** [PolyhedralDev/Terra#139]
In pull #133 spawn rates were improved (this sort of fixed issue #129).
From what I can tell, all biomes in Terra pull their spawn info from whatever the first vanilla biome is.

Instead each terra biome should have a vanilla biome its pulling properties from that most matches it instead of just whatever happens to be first.

Rather than pulling from the first vanilla biome in all cases it would make more sense to have another function which accepts a biome to extend properties from that way its possible to just give whatever the biome that's being created is "most like."

For example a generic snowy terra biome might use the snowy tundra biome. I would think this would fix Husks, Strays, Polar bears, etc not spawning.

This would fix the issue for existing worlds too so its perfect.

**Comment by solonovamax** [comment]
Fabric or spigot?

Because spigot,,, well..... it does its own funky stuff which breaks all this lol

**Comment by Hexcede** [comment]
> Fabric or spigot?
> 
> Because spigot,,, well..... it does its own funky stuff which breaks all this lol

We're (me and a group of friends) are using the Fabric version. We're running it on a Fabric server as a Fabric mod with Cardboard for a few other bukkit plugins iirc, I'm not sure if Cardboard might be impacting it but I wouldn't think so since we're not running the spigot version itself, it should just be the regular mod.

Overall it seems like spawn rates are really really low for passive mobs and I think that the pull request I mentioned indicates the cause. (The pull request was a fix to that but it only improved it quite a bit, the spawn rates are still super low regardless). The biome spawn info is only being copied from one biome, and, as far as I could tell all of the Terra biomes are not pulling from any other vanilla ones, just whatever happens to be the first loaded biome. If they pulled their biome properties from biomes they matched better that might improve a lot of the issues.

I'm not sure if the reason biome specific mobs aren't spawning is a result of the overall spawn rates being too low or just those mobs simply not being allowed to spawn. I believe things like Pandas and Polar Bears spawn in specific biomes which would be defined by their biome's spawn properties I'd assume but I'm not really sure.

**Comment by Hexcede** [comment]
@solonovamax I don't know if you saw my previous reply but the answer to your question is Fabric, not Bukkit.

**Comment by Hexcede** [comment]
Closing since #166 has more information
