### ISSUE TITLE
MythicMobs Support

### ISSUE THREAD

**Issue by AshenGaming** [PolyhedralDev/Terra#15]
Hi there,

Would be a great addition if Terra supported MythicMobs spawning similar to how BetterEnd does for each biome.

**Comment by dfsek** [comment]
This will probably be included through an addon in the future. I want to keep Terra as clean as possible, and handle all integrations via addons. This is definitely on the to-do, though,

**Comment by AshenGaming** [comment]
Sounds good to me :)

**Comment by solonovamax** [comment]
depending on how mythic mobs works, it might actually be a good idea to add it in the default config.
If it simple works by spawning a mob with custom data, then we could do that. If we need to interface with some API, then it'll have to be done in an addon.

**Comment by dfsek** [comment]
It's an API, which is why it should be done via addon.

**Comment by solonovamax** [comment]
rip

**Comment by iDirtniverse** [comment]
bumpy

**Comment by solonovamax** [comment]
@iDirtniverse 
> This will probably be included through an addon in the _future_.

> This is definitely on the to-do, though,

**Comment by dfsek** [comment]
https://github.com/PolyhedralDev/TerraMythicMobsAddon

Works with 4.2.0 (currently in dev) and up.
