### ISSUE TITLE
Outposts not spawning pillagers (fabric)

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [PolyhedralDev/Terra#150]
When i find a terra outpost pillagers don't spawn there like they are supposed to. I have also tried killing all the entities to make sure it's not because of the mob cap, but they just don't seem to be spawning.

**Comment by Astrashh** [comment]
Not a bug, Terra just lacks the functionality for persistent mob spawning. #111 solves this.

**Comment by DUDEbehindDUDE** [comment]
How long until it's finished

**Comment by solonovamax** [comment]
nobody's working on it ATM, but if you want to, you can contribute code.

**Comment by dfsek** [comment]
Duplicate of #111
