### ISSUE TITLE
Terra crashes modpack.

### ISSUE THREAD

**Issue by toErIpNid** [PolyhedralDev/Terra#154]
[crash-2021-05-04_00.58.24-client.txt](https://github.com/PolyhedralDev/Terra/files/6419201/crash-2021-05-04_00.58.24-client.txt)

Fabric version: 0.11.3

Minecraft version: 1.16.5

Mod version: 5.2.1 (latest)

**Comment by solonovamax** [comment]
Remove half the mods and try again. Then do it with the other half of the mods. Once you find which half crashes, halve that half and do it again. Keep doing this until you found out which mod crashes.
