### ISSUE TITLE
Crashes using BetterEnd pack

### ISSUE THREAD

**Issue by onicalls** [PolyhedralDev/Terra#155]
https://pastebin.com/RzjN9Ke9

Plugin Version: v5.2.1-BETA
Server Version: Yatopia-ver/1.16.5-106

**Comment by solonovamax** [comment]
how the-

**Comment by onicalls** [comment]
I forgot send crash report

[crash-2021-05-04_09.03.51-server.txt](https://github.com/PolyhedralDev/Terra/files/6421223/crash-2021-05-04_09.03.51-server.txt)

**Comment by solonovamax** [comment]
does it work without yaptopia

**Comment by dfsek** [comment]
Compile the fractal trees addon with shaded dependencies.
