### ISSUE TITLE
Error appears and server lags out when a dolphin is fed. 

### ISSUE THREAD

**Issue by itaquito** [PolyhedralDev/Terra#160]
Hello! This error happens when a player feds a dolphin. I believe this is caused when the server tries to find a structure.
Error: https://paste.itaqui.to/fmRwOPmiP3.sql
Server version: This server is running Paper version git-Paper-645 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT).
Plugin version: v5.2.1-BETA+a7e3a028
Timings (with the list of plugins): https://timings.aikar.co/?id=a1b07b7ef65f42678f0370c2d746817d

Thanks!

**Comment by dfsek** [comment]
> No overrides are defined for "minecraft:shipwreck"

There's your issue. I'm unable to replicate the crash, though the server does chug for a few seconds. I'm guessing you're running on a potato, and that 3 seconds turns into 60, triggering watchdog.

The event handler should probably be rewritten to just pass the origin location as the result if no override is defined, that way it just fails and logs a message to the console.

**Comment by Roan-V** [comment]
Related to https://github.com/PaperMC/Paper/issues/2312

**Comment by itaquito** [comment]
If I remember correctly I didn't change the config of Terra, I'm not sure if I should change something to prevent this problem.

The server performance is interesting.. this happened on a private server, which most of the time is running at 20TPS with around 30% of CPU usage (I believe we have 3 vCores at 3ghz, don't trust me on this one). We didn't do any optimization at all, that's probably why we have some above-average count of entities. 

Nonetheless, thanks for your support! If I can do something on my end please tell me.

**Comment by dfsek** [comment]
This was fixed in #182 but i forgot to close the issue
