### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hjhyhg** [PolyhedralDev/Terra#163]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5/5/21 8:22 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$12562/600422280.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:579)
	at net.minecraft.class_3898$$Lambda$12564/1744288144.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$12549/635591244.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 12 more
Caused by: java.lang.NullPointerException
	at supercoder79.cavebiomes.world.feature.AddCaveBiomesFeature.generate(AddCaveBiomesFeature.java:60)
	at supercoder79.cavebiomes.world.feature.AddCaveBiomesFeature.method_13151(AddCaveBiomesFeature.java:31)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_2988.method_30384(class_2988.java:23)
	at net.minecraft.class_2988$$Lambda$12586/2115451260.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.class_2988.method_12892(class_2988.java:22)
	at net.minecraft.class_2988.method_13151(class_2988.java:14)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_1959.method_8702(class_1959.java:373)
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at com.dfsek.terra.fabric.generation.FabricChunkGeneratorWrapper.method_12102(FabricChunkGeneratorWrapper.java:114)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$2204/1757884034.doWork(Unknown Source)
	at net.minecraft.class_2806.md60084c$lambda$injectLightmapSetup$1$4(class_2806.java:2046)
	at net.minecraft.class_2806$$Lambda$2205/1817447589.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 584500208 bytes (557 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Mixins in Stacktrace: 
		net.minecraft.class_3900:
			me.jellysquid.mods.lithium.mixin.world.chunk_task_system.ChunkTaskPrioritySystemMixin (lithium.mixins.json)
	Fabric Mods: 
		addendum: Addendum 1.16.5-1.0.2
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.3
		advdebug: Advancements Debug 2.2.0
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.2.0-alpha.3
		architectury: Architectury 1.12.145
		artifacts: Artifacts 3.2.0+fabric
		artifice: Artifice 0.14.6+1.16.5
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		attributefix: Attribute Fix {FABRIC} 1.0.1
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		bambootweaks: Bamboo Tweaks 2.0.5
		battletowers: Battle Towers 3.3.4-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		bewitchment: Bewitchment 1.16.5-8
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.5-1.3.6
		blast: BLAST 1.5.2
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 2.1.1+1.16.5
		blue_endless_jankson: jankson 1.2.0
		boringbackgrounds: Boring Backgrounds 3.0.2+1.16.3
		builtinservers: Builtin Servers 1.0-BETA
		byg: BYG 1.1.7
		campanion: Campanion 1.3.5
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components: Cardinal Components API 2.8.0
		cardinal-components-base: Cardinal Components API (base) 2.8.0
		cardinal-components-block: Cardinal Components API (blocks) 2.8.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.0
		cardinal-components-entity: Cardinal Components API (entities) 2.8.0
		cardinal-components-item: Cardinal Components API (items) 2.8.0
		cardinal-components-level: Cardinal Components API (world saves) 2.8.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.0
		cardinal-components-util: Cardinal Components API (utilities) 2.8.0
		cardinal-components-world: Cardinal Components API (worlds) 2.8.0
		carrier: Carrier 1.7.5
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.3.2
		charmonium: Charmonium 2.3.2
		cherishedworlds: Cherished Worlds 1.3.0-1.16.4
		chillager_mod: Chillager 1.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		colorfulcolumns: Colorful Columns 1.0.0
		columns: Columns 1.1.1
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_nathanpb_safer: Safer 1.1.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:Restitched 1.94.1-beta
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.3
		craftpresence: CraftPresence 1.8.0
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		croptopia: Croptopia 1.3.1
		croptosis: Croptosis 1.1.0
		crusade: Crusade 1.2.0
		dadobugbiomes: Dadobug1111's Biomes 1.3.0
		dankstorage: Dank Storage 1.9a-1.16.3
		darkpaintings: Dark Paintings 3.0.1
		dawn: Dawn API 1.8
		decimal_coins: Decimal Coins 1.16.2-1.2.0
		desolation: Desolation 1.1.1
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.3-beta1
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.0
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		dynamicfps: Dynamic FPS 2.0.1
		ecotones: Ecotones 0.7.2
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchantmentdescriptions: Enchantment Descriptions 2.0.1
		expandedstorage: ExpandedStorage 5.6.33
		eymbra: Eymbra's Prehistoric Mod 1.0.0
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.33.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fasttransferlib: Fast Transfer Lib 0.3.1
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.218
		fermion-gui: Fermion GUI 2.5.218
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-simulator: Fermion Simulator 1.8.218
		fermion-varia: Fermion Varia 2.6.218
		ferritecore: FerriteCore 2.0.4
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		flytre_lib: FlytreLib 0.2.9
		frex: FREX 4.5.201
		ftbguilibrary: FTB GUI Library 1605.2.1.41
		ftbquests: FTB Quests 1605.2.1-build.39
		gateofbabylon: Gate Of Babylon 1.4.2-1.16.5
		geckolib3: Geckolib 3.0.31
		givemehats: Give Me Hats! 1.5.1
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		golemsgalore: Golems Galore 0.2.1+mc.1.16.5
		goml: Get Off My Lawn 1.3.4-beta
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 1.1.0
		hctm-base: HCTM Base 3.5.1
		healthoverlay: Health Overlay 3.6.14
		horseinfo: Horse Info 0.2.2-1.16.1
		ignis-fatuus: Ignis Fatuus 1.1.3
		imggen: Image World Generator 1.1.3
		imm_ptl_core: Immersive Portals Core 0.90
		immersive_portals: Immersive Portals 0.90
		impersonate: Impersonate 2.1.0
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.9.4-BETA
		inmis: Inmis 2.2.1-1.16.5
		inventorysorter: Inventory Sorter 1.7.9-1.16
		iron-jetpacks: Iron Jetpacks 0.3.1
		itemfilters: Item Filters 1605.2.4-build.30
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		json-model-extensions: JSON Model Extensions 1.21.182
		jumploader: Jumploader 2.1.3
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.6.7-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1605.3.7-build.184
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lakeside: Lakeside 1.0.3+1.16.4
		lapisreserve: Lapis Reserve 1.0.6
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.2.1
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.7
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		library_of_exile: Library of Exile 1.0.7
		libstructure: LibStructure 1.5
		lifts: Lifts 1.1.0-BETA
		lightoverlay: Light Overlay 5.8.0
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4
		magna: Magna 1.5.1-1.16.5
		make-every-biome-spawnable-lol: Make Every Biome Spawnable 1.16.5-1.1.0
		marshmallows_rpg: Marshmallow's RPG 1.0.0
		maybe-data: Maybe data 1.0.0-1.16.2
		mcdict: MCDict 2.0.1+1.16.4
		megane: megane 3.1.6+1.16.5
		megane-api: megane-api 3.1.6+1.16.5
		megane-impl: megane-impl 3.1.6+1.16.5
		megane-runtime: megane-runtime 3.1.6+1.16.5
		minecraft: Minecraft 1.16.5
		mixintrace: MixinTrace 1.0.0
		mm: Manningham Mills 2.2
		mo_glass: Mo Glass 1.5-MC1.16.5
		mocolors: Mo' Colors 1.1.2
		modern_beta: Modern Beta Fabric 1.1.1
		modern_industrialization: Modern Industrialization 0.3.16
		modmenu: Mod Menu 1.16.9
		more_gems: More Gems 1.1.22
		more_tooltips: MoreTooltips 1.0.1
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		multi_item_lib: Multi Item Lib 1.2.0
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		netherite_plus: Netherite Plus Mod 1.4.3-1.16.5
		no-potion-offset: No Potion Offset ${version}
		noanglebrackets: NoAngleBrackets 1.0.1
		notes: Notes 1.0.4
		nourish: Nourish 1.2.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		oro_config: OroArmor Config 2.0.0
		packages: Packages 1.1.1
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.9.0+21w10a
		phosphor: Phosphor 0.7.1+build.11
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quickshulker: Quick Shulker 1.1.14-1.16
		randompatches: RandomPatches 2.4.5-fabric
		ratsmischief: Rat's Mischief 1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.0
		reborncore: Reborn Core 4.7.2+build.132
		repurposed_structures: Repurposed Structures 1.16.5-1.10.3-fabric
		reroll: Reroll 1.2.1-1.16.5
		respawnablepets: Respawnable Pets 1.16.5-2
		rhino: Rhino 1.7.13-build.23
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.11.202
		roughlyenoughitems-api: REI (API) 5.11.202
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.202
		roughlyenoughitems-runtime: REI (Runtime) 5.11.202
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rswires: RSWires 4.10.2
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 1.0.2
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		sandwichable: Sandwichable 1.2-beta5
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		secretrooms: Secret Rooms 0.9.3+1.16.5
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		simpleteleporters: Simple Teleporters 2.2.1
		simplexterrain: Simplex Terrain 0.7.2
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		slotlock: SlotLock 1.0.3-BETA
		smootherbedrock: Smoother Bedrock 1.0.0
		sodium: Sodium 0.1.1
		sojurn: Sojurn b1.1
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		somnus: Somnus API 0.0.11-1.16.5
		special-circumstances: Special Circumstances 1.8.218
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		structurized: Structurized 1.2.0-1.16.5
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.5.1+mc.1.16.5
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.2+build.220
		terra: Terra 5.3.0-BETA+fd48f5f1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.4
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		terrestria: Terrestria 2.2.0
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.4.2
		the_garden: The Garden 0.1.3-hotfix-hotfix
		tis3d: TIS-3D 1.6.1
		tis3d-additions: TIS-3D Additions 0.2.1+1.16.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		tooltipfix: ToolTip Fix 1.0.2-1.16
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.3
		tweed: Tweed API 3.0.0-beta.22
		ultra_amplified_dimension: Ultra Amplified Dimension 1.16.4-9.1.1-fabric
		unearthed: Unearthed 1.1.1
		vanilla-hammers: Vanilla Hammers 3.0.2-1.16.5
		vanilladeathchest: VanillaDeathChest 2.0.6-fabric
		vanillaenhanced: VanillaEnhanced 1.4.0
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		vistas: Vistas 1.3.1
		voyager: Voyager 1.0.0
		waystones: Waystones 1.1.1.1
		wild_explorer: Wild Explorer 1.3.3
		winged: Winged Mod 1.16.2-1.4.1
		wirelessnetworks: Wireless Networks 1.0.2
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		wthit: wthit 2.7.0
		xaerominimap: Xaero's Minimap 21.8.0
		xaeroworldmap: Xaero's World Map 1.13.2
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), null, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by dfsek** [comment]
When you report issues, provide actual context. Throwing a crash report at us usually isn't very helpful.

**Comment by dfsek** [comment]
Also, put crash reports on hastebin, don't just dump them in an issue and click submit.

**Comment by hjhyhg** [comment]
> When you report issues, provide actual context. Throwing a crash report at us usually isn't very helpful.

when i loaded a world up

**Comment by dfsek** [comment]
> Cave Biomes 0.6.2

Where did you even get that? The latest version is 0.6.1, and the stack trace does not match up.

https://github.com/SuperCoder7979/cavebiomes/blob/cf34ecd21d319fca9f76163d011684ecd65473a6/gradle.properties#L13

**Comment by hjhyhg** [comment]
> > Cave Biomes 0.6.2
> 
> Where did you even get that? The latest version is 0.6.1, and the stack trace does not match up.
> 
> https://github.com/SuperCoder7979/cavebiomes/blob/cf34ecd21d319fca9f76163d011684ecd65473a6/gradle.properties#L13

that is the wrong mod

**Comment by dfsek** [comment]
....

Where can I find the correct mod?

We can't read your mind, you have to actually be helpful when reporting an issue. Do you want us to be able to fix this? Give us useful information.

**Comment by hjhyhg** [comment]
> ....
> 
> Where can I find the correct mod?
> 
> We can't read your mind, you have to actually be helpful when reporting an issue. Do you want us to be able to fix this? Give us useful information.

this is the right one and  i got a crash when i create a new world

**Comment by dfsek** [comment]
What? Where is the correct mod? Give a link. Give a detailed explanation of things, try to be helpful here.

**Comment by hjhyhg** [comment]
> What? Where is the correct mod? Give a link. Give a detailed explanation of things, try to be helpful here.

here when i created a new world with the world type "TERRAdefault" it crashed the correct mod is  https://www.curseforge.com/minecraft/mc-mods/terra-world-generator
