### ISSUE TITLE
Forge Chunk generator is not saved on relog.

### ISSUE THREAD

**Issue by pocketwheat** [PolyhedralDev/Terra#168]
For some odd reason the terrain generation will work up until a certain point and then it will start generating the default terrain

**Comment by dfsek** [comment]
... What?

**Comment by dfsek** [comment]
What platform are you on?

What mods do you have installed?

Put a log on hastebin

Client or server?


If you want us to be able to do anything about an issue you have to actually provide relevant information

**Comment by pocketwheat** [comment]
> What platform are you on?
> 
> What mods do you have installed?
> 
> Put a log on hastebin
> 
> Client or server?
> 
> If you want us to be able to do anything about an issue you have to actually provide relevant information

mb bro i use forge with client I didnt have any mods installed and what is hastebin

**Comment by TwirreM** [comment]
I have the same problem, and have been able to reproduce it.

The problem: Part of the world is generated with Terra, and the rest is generated with normal Minecraft generation. The part that is Terra is the part that was generated when playing the world the first time. After closing the world, and reentering, any new terrain is default Minecraft terrain.

So to reproduce: Make a world with Terra terrain. Fly a tiny bit, see that it generates Terra biomes. Then save and close the world, and then reenter it. Fly around more, now newly generated terrain is Minecraft.

Here's a log from when I recreated the issue on a new world:
https://pastebin.com/ZNttF1V9
