### ISSUE TITLE
PopulatorFeature includes no checks as to whether world is generated by Terra

### ISSUE THREAD

**Issue by TelepathicGrunt** [PolyhedralDev/Terra#169]
I gotten a report on my World Blender mod that Terra crashes it when entering the dimension.
https://github.com/TelepathicGrunt/WorldBlender-Fabric/issues/10

I was able to reproduce it with just our two mods on and here's my latest.log output of the crash: https://paste.ee/p/YJUUG

I believe the issue is specifically caused by 
```java.lang.ClassCastException: net.minecraft.world.gen.chunk.NoiseChunkGenerator cannot be cast to com.dfsek.terra.fabric.generation.FabricChunkGeneratorWrapper```

The checkBlockCollision crashing is because my block tries to teleport the player to the other dimension in it's collision method and that dies because of the ClassCastException when it goes to load a chunk in World Blender's dimension

Here's the crash remapped to be yarn and easier to read: https://paste.ee/p/WEncw

I'm not sure if there's anything on my end that I can help with but hopefully this helps!

**Comment by TelepathicGrunt** [comment]
Oh yeah, last thing, this is in a default worldtype too which make this even more odd

**Comment by dfsek** [comment]
Your World Blender mod is registering our `PopulatorFeature` in its dimension, which currently assumes it will only be run in a Terra world. I can add a simple type check to it to fix this.

**Comment by dfsek** [comment]
Tested with other dimension mods to confirm, it is indeed just World Blender. Which makes sense, since the point of the mod is to include *all* configuredfeatures, and our `PopulatorFeature` currently includes no checks to when it is used outside of Terra worlds.

**Comment by TelepathicGrunt** [comment]
Ah oops. I'll add terra's configuredfeature to my config blacklist so it is in the config by default but it wont fix configs already made by people having world blender on before. But hopefully going forward, it will help prevent any more crashes until terra adds the check to disable the CF outside their intended chunk generator. 

It would also prevent the crash if someone tries to shove the CF into a biome with a worldgen datapack which would be concerned lol. Probably won't ever happen but it is a possibility

**Comment by TelepathicGrunt** [comment]
I blacklisted the populator and it seems it still crashes but on just the block collision. 
Log: https://paste.ee/p/qJRmI
Mapped: https://paste.ee/p/xNZh9

I think this is a different issue so I'll poke around and make it print the actual crash stacktrace instead of crashing while preparing the crash report. I'll open a separate issue once I figure this one out
