### ISSUE TITLE
compat with Subterranean wilderness and yungs better caves

### ISSUE THREAD

**Issue by thiccmeme** [PolyhedralDev/Terra#170]
thus far I have tested these three together with no success, the carver gen of terra completely overwrites that of either of these mods, If there is any way to separate the carver gen from the upper of the overworld this would be phenomenal. both of these mods add an amount of detail which either isn't achievable with just terra in the case of Sub Wild or requires a lengthy process of trial and error configuration in the case of yungs better caves.

if these could be made compatible with terra it would be phenomenal

**Comment by dfsek** [comment]
Carver compatibility options were implemented in #199
