### ISSUE TITLE
Console command /locatebiome

### ISSUE THREAD

**Issue by Skelark** [PolyhedralDev/Terra#185]
Using that command the game breaks but using the /locate it seems to work fine. The world stops generating, you can't access chests and other inventories. When I quit the game it freezes in the "saving world" screen and I need to use task manager to close it. After that the launcher opens saying that the game crash with exit code 0 and when I look for a crash log report I don't find any.
Using fabric version - Terra-fabric-5.3.0-BETA+fd48f5f1-shaded-mapped.jar

**Comment by dfsek** [comment]
Unable to replicate. You're also on an outdated version. Update to the latest version.

**Comment by Skelark** [comment]
On the curse forge web site the 5.3.0 is the most recent release  but on the modrinth web site is a newer one.
I have download the newer one and the error continues here is a 15 minutes video of replicating the error a few times.

https://drive.google.com/file/d/13RnOEhgjrozo3esyVu_4gVzHJLfpkEEe/view?usp=sharing
