### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Phoenix1045** [PolyhedralDev/Terra#186]
I am using fabric to use the terra mod, I dragged it into the mod folder, but it is not working at all. I have tried deleting and redownloading it, tried using it as a data pack, and it still won't work. Am I being stupid and doing something wrong? Or is it something with terra?

**Comment by dfsek** [comment]
I'm guessing you aren't selecting the Terra world type. If you have basic support questions like this, ask in the Discord before opening an issue.

**Comment by Phoenix1045** [comment]
oh
