### ISSUE TITLE
Yungs better caves Yungs better mineshaft and sub wild compatibility plz!!!

### ISSUE THREAD

**Issue by Hydra106** [PolyhedralDev/Terra#190]
Now it doesn't have compatibility with Yungs better caves Yungs better mineshaft and sub wild it uses its own caves I would like to be able to use this with Yungs better caves Yungs better mineshaft and sub wild but great job with the dungeons/spanners wouldn't change that .

**Comment by solonovamax** [comment]
We will not add compatibility with Yung's better caves, as those mods do not work with terra because they are attempting to hook into vanilla and not terra world gen.

If you want yung's better caves/etc. to work on terra, go ask the devs of those mods. (But don't bother them.)
