### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by jamesmov** [PolyhedralDev/Terra#192]
Every spawner by default is a pig spawner

**Comment by dfsek** [comment]
Please provide actually helpful information in issue reports. If this happened all the time we would have fixed it by now, so provide instructions to reproduce, tell us what platform you are on, provide logs, list of mods, etc. This issue report is the opposite of helpful.

**Comment by solonovamax** [comment]
(needs work is for when the code is in WIP)

**Comment by jamesmov** [comment]
oh, I'm sorry, this is my first time ever doing something like this so I apologize for the lack of helpful information. 

In my experience this happened every single time there was a spawner (namely dungeons) except for in the nether. 

The mod list is in Fabric, mod list goes: 
- fabric API 0.34.2
- optifabric 1.9.6
- optifine G7
- replaymod 2.5.2
- Terra-fabric-5.3.0-BETA+fd48f5f1-shaded-mapped
[latest.log](https://github.com/PolyhedralDev/Terra/files/6505352/latest.log)

**Comment by dfsek** [comment]
Remove OptiFine.
