### ISSUE TITLE
i have a few issue

### ISSUE THREAD

**Issue by mcaskilSeed** [PolyhedralDev/Terra#195]
first issue, there was no forge version on [curseforge](https://www.curseforge.com/minecraft/mc-mods/terra-world-generator) but in the title "fabric/forge/spigot"

second issue, i can't dissable terra structure

and actualy terra structure is not bad but in village there was no villager at all and if we /locate village it didn't work and crah my game

thanks for reading this and i hope the devloper of this mod can fix it, overall it's a great mod

**Comment by dfsek** [comment]
These can all be solved very quickly by reading:
* the gigantic text at the top of the curseforge page 
* the wiki

**Comment by mcaskilSeed** [comment]
but mr. polyhedral how about the villager?

**Comment by mcaskilSeed** [comment]
terraforge is better than this mod :<

**Comment by mcaskilSeed** [comment]
ummm im sorry mr polyhedral,  can you give me quick tutorial how to config the mod and not the plugin? cus your wiki is didn't explain anything to me
