### ISSUE TITLE
[Feature Request] Have an option for specifing treat count.

### ISSUE THREAD

**Issue by TheRealM18** [PolyhedralDev/Terra#198]
Server Software: Paper
Terra Version: Terra-bukkit-5.3.0-BETA+fd48f5f1-shaded.jar

I would like on my server to help performance improvements, to have settable amount of threads to use, to allow for more dynamic use of core to speed it up.  It currently uses 300% plus in times for chunk population (shown here https://timings.aikar.co/?id=ef88a13b45634346b76ec5d8f06be036 ).

Thank you in advanced

**Comment by dfsek** [comment]
https://paper.readthedocs.io/en/latest/server/configuration.html#async-chunks
