### ISSUE TITLE
trying to generate a world with terra wont let the world generate 

### ISSUE THREAD

**Issue by Firezone87** [PolyhedralDev/Terra#201]
when creating a world with terra the screen becomes like this and the world never loads, I'm using a modpack with 100 mods, i have some world generations mods for other dimensions but the only one that changes the overworld is terra. (i tried to create a world with the same modpack but without terra and it worked just fine, i even tried to use other versions of the mod but it didn't work)
![Immagine 2021-05-22 182238](https://user-images.githubusercontent.com/69213979/119233744-b71bb900-bb2a-11eb-9c85-28bb62f68279.png)
these are the mods that im currently using:
![image](https://user-images.githubusercontent.com/69213979/119234017-e7b02280-bb2b-11eb-9d83-31807877df55.png)

**Comment by dfsek** [comment]
Figure out which mod is causing issues. Dumping a massive list of mods for us to sift through is not helpful.
