### ISSUE TITLE
Crash when clicking "Create New World" from singleplayer menu with Biomes O' Plenty in mods folder

### ISSUE THREAD

**Issue by xameryn** [PolyhedralDev/Terra#202]
Crashes to MC launcher with the message:
The game crashed whilst mouseclicked event handler
Error: java.lang.ClassCastException: net.minecraft.util.text.StringTextComponent cannot be cast to net.minecraft.util.text.TranslationTextComponent
Exit Code: -1

Resolved once Biomes O' Plenty is removed.

Minecraft:
1.16.5

Mod Version:
5.3.3-BETA+ec3b0e5d

Modloader:
Forge

[crash-2021-05-26_18.50.57-client.txt](https://github.com/PolyhedralDev/Terra/files/6550606/crash-2021-05-26_18.50.57-client.txt)

**Comment by dfsek** [comment]
This is an issue with Biomes O Plenty. They are (incorrectly) assuming that the generator type's `TextComponent` is a `TranslationTextComponent`, when ours are `StringTextComponent`s. This can be fixed on their end with a simple `instanceof` check.
