### ISSUE TITLE
[Paper] structure locate command unable to point to structures far away from spawn

### ISSUE THREAD

**Issue by CrashingBrain** [PolyhedralDev/Terra#203]
the `te structure locate <STRUCTURE>` command seems unable to find structures far away from spawn.
In proximity (few hundreds/thousands blocks) form 0,0 `te structure locate` is able to point to various different  structures (village, dungeon, stronghold, etc) but If I move 10-20k blocks aways the command still points to those close to spawn.
The vanilla `locate` command is able to find the nearby structures tho.

Terra Version 5.3.3
Server Paper 1.16.5 - 662

![Screenshot 2021-05-27 at 15 36 18](https://user-images.githubusercontent.com/23700285/119836778-4ac20080-bf02-11eb-8db4-9c5f429434dd.png)

**Comment by solonovamax** [comment]
teleport out to like 100k or 1mil, can you reproduce that far?

**Comment by CrashingBrain** [comment]
yes. it's the same
