### ISSUE TITLE
Clickable Coordinates

### ISSUE THREAD

**Issue by kystra** [PolyhedralDev/Terra#206]
Currently when you locate a biome through terra, the coordinates are white / non clickable. 
Normal /locate coordinates are both highlighted green and clickable, actioning as /tp @s ~ ~ ~.
Would be a nice touch to add :)

EDIT: probably worth mentioning I'm on Fabric.

**Comment by bubbaguy1234** [comment]
I know this sounds like it should be pushed to the back of the list but this would be super useful for newcomers and old users of this mod

**Comment by Sancires** [comment]
Not exactly the same but you can always add `-t` to the end of the locate to automatically teleport.

**Comment by dfsek** [comment]
We no longer have commands which would require clickable coordinates (we use Vanilla's `/locate` and `/locatebiome` now), and if an addon wishes to implement one they can use Adventure with cloud.
