### ISSUE TITLE
[Bug] java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by zndrmn** [PolyhedralDev/Terra#213]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | forge-5.3.3-BETA+ec3b0e5d
| Platform / Platform Version  | 1.16.5-forge-36.1.2
| Any External Plugins or Mods | https://gist.github.com/zndrmn/a0fb51b28980545594d314ff2c49f443#file-forgemodlist-txt
| Terra Packs In Use           | Whatever the Default one is, Forgot the name of it.
| Terra Addons In Use          | None
## Issue Description

"_java.lang.NullPointerException: Initializing game_" Error during start up.

### Steps to reproduce

1. Open Minecraft
2. Launch Minecraft
3. Minecraft crashes, reports error

### Expected behavior

Should be able to Fully launch without problems

### Actual behavior

Doesn't Launch 

### Full stacktrace

https://gist.github.com/zndrmn/db8348ea9c23a8e5f45dc4335c8ca537#file-latest-log
https://gist.github.com/zndrmn/575378689efc953e169a2dee935cf549#file-debug-log
https://gist.github.com/zndrmn/2327143ccc7ee0295aa3a9806e33c483#file-crash-2021-06-13_00-23-08-client-txt

```

```

</details>

**Comment by dfsek** [comment]
[We've decided to drop the Forge implementation.](https://gist.github.com/dfsek/c96d364c48f8a1738fc36609af289f96) If anyone wants to continue the Forge implementation, feel free to comment and tackle this issue, we'll re-open it for you.
