### ISSUE TITLE
[Bug] Ores don't generate below y0

### ISSUE THREAD

**Issue by EVERYPLANET** [PolyhedralDev/Terra#224]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 5.4.1
| Platform / Platform Version  | Paper 1.17-26
| Any External Plugins or Mods | Chunky, CMI, multiverse, worldedit, viaversion/backwards
| Terra Packs In Use           | Custom development pack
| Terra Addons In Use          | none

## Issue Description

When generating terrain, ores do not generate below y level 0.

### Steps to reproduce

1. Run any pack including ores that generate lower than y 0
2. Clear out stone from a chunk using world edit.
3. It is very clear that ore does not spawn below y 0

### Expected behavior

Ore should continue generating below y 0

### Actual behavior

Ores do not generate below y 0

### Full stacktrace

Latest log:
[latest.log](https://github.com/PolyhedralDev/Terra/files/6687462/latest.log)

### Additional details

Using a datapack to edit build limits. 
![image](https://user-images.githubusercontent.com/60523794/122779802-27426980-d2a6-11eb-9bd9-98d29981f378.png)
![image](https://user-images.githubusercontent.com/60523794/122779861-332e2b80-d2a6-11eb-9dc9-54f8d118d624.png)

**Comment by EVERYPLANET** [comment]
This issue also applies to beta carving and flora. That's all I've tested but it's possible that it applies to other features too.

**Comment by dfsek** [comment]
fixed in 6.0
