### ISSUE TITLE
[Bug] /locatebiome does not work

### ISSUE THREAD

**Issue by czhangdev** [PolyhedralDev/Terra#225]
## Pre-Issue Checklist

- [ x] I have checked that I am on the latest version of Terra.
- [ x] I have searched the github issue tracker for similar issues, including closed ones.
- [ x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [ x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [ ] I have attached a copy of the `latest.log` file
- [ x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | Terra version 5.4.1-BETA+efd1665c
| Platform / Platform Version  | PaperMC version git-Paper-"4e2f0be"  (MC: 1.17)
| Any External Plugins or Mods | BloodMoon, CoreProtect, Essentials, EssentialsChat, GriefPrevention, LuckPerms, PlaceholderAPI, PowerRanks, ProtocolLib, SmoothTimber, Terra, ThirstforWater, Vault
| Terra Packs In Use           | DEAFAULT, NETHER
| Terra Addons In Use          | Terra-Bukkit v1.0.0 by Terra

## Issue Description

locatebiome report wrong location

### Steps to reproduce

1. /locatebiome minecraft:badlands
2. /tp <location located using locatebiome>

### Expected behavior

should see badlands biome after teleportation 

### Actual behavior

instead see a biome unrelated to the biome you are trying to find
### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```

```

</details>

### Additional details
none error produced in the chat or in the console, happens with other biome, not just badlands. btw, since I am accessing github from china, I am unable to upload the latest.log....

**Comment by Roan-V** [comment]
Use "/te biome locate" as an alternative to "/locatebiome"

**Comment by czhangdev** [comment]
> Use "/te biome locate" as an alternative to "/locatebiome"

thanks, that worked, however, it takes way longer than locatebiome, it took about a minute to find biome "YELLOWSTONE" and in still in process of finding biome "YELLOWSTONE" (Has been going on for about 2 minute already), and the server configuration is fairly high, is there any chance you guys could optimize it?

**Comment by Roan-V** [comment]
Have you tried any other biome than yellowstone?
Yellowstone is pretty rare iirc

**Comment by czhangdev** [comment]
> Have you tried any other biome than yellowstone?
> Yellowstone is pretty rare iirc

oh nvm I guess, still slower than locatebiome, but way faster than before.... I think my problem is solved, closing the issue, thanks, will surely leave a good review, and mention that you guys have a wonderful support and developer.
