### ISSUE TITLE
[Feature] Allow structure exporting in non Terra worlds

### ISSUE THREAD

**Issue by Sancires** [PolyhedralDev/Terra#235]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x]  I have searched github for similar features requests, including closed ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that should be implemented by a pack or addon.

### What Problem Does This Solve?

Currently, exporting structures is limited to Terra worlds, lifting this restriction would allow for easier and faster exporting of structures from commonly used grids (which are usually in super flat / void worlds. While the grids can be copied and pasted into a new Terra world, this just saves an extra step.

### A Solution You'd Like

Not checking the world type on `/te structure export`

### Alternative Solutions

1. A config option.
2. Including this within the debug option.

**Comment by dfsek** [comment]
structure exporting to terrascript is no longer supported, sponge schematics should be used for static structures.
