### ISSUE TITLE
[Bug] no dimensions except minecraft:overworld created

### ISSUE THREAD

**Issue by Kloenk** [PolyhedralDev/Terra#239]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra. (5.4.1-BETA+40e95073-shaded-mapped)
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [ ] I have attached a copy of the `latest.log` file
- [ ] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 5.4.1-BETA+40e95073-shaded-mapped
| Platform / Platform Version  | fabric v0.11.6 (mc 1.17.1)
| Any External Plugins or Mods | appleskin-fabric-mc1.17-2.0.0.jar  fabric-api-0.36.1+1.17.jar lifts-1.1.2-BETA+1.17.jar       preview_OptiFine_1.17_HD_U_G9_pre24.jar.disabled             Terra-fabric-5.4.1-BETA+40e95073-shaded-mapped.jararchitectury-2.1.20-fabric.jar     fabric-carpet-1.17.1-1.4.43+v210706.jar         modmenu-2.0.2.jar               professionalmc-1.0.0.jar.disabled                            tomsstorage-1.1.13-1.17.1.jarauthme-1.17-1.5.0.jar              fabric-language-kotlin-1.6.2+kotlin.1.5.20.jar  NE-1.17-Fabric-1.2.0.jar        RoughlyEnoughItems-6.0.264-alpha-fabric.jar                  wthit-fabric-3.6.1.jar cloth-config-5.0.34-fabric.jar     fabric-seasons-1.2.2-BETA+1.17.jar              notforgotten-1.0.0.jar          taterzens-1.2.0-fabric.jar                                   Xaeros_Minimap_21.12.5.1_Fabric_1.17.1.jar comforts-fabric-0.0.4-1.17.jar     indrev-1.10.0-alpha.8.jar                       optifabric-1.11.9.jar.disabled  Terra-fabric-5.3.3-BETA+6027c282-shaded-mapped.jar.disabled  XaerosWorldMap_1.14.5.2_Fabric_1.17.1.jar
| Terra Packs In Use           |  DEFAULT (v2.0.0), NETHER (v2.0.0)
| Terra Addons In Use          | Terra-Fabric (v1.0.0)

## Issue Description
No Nether and end dimension available

### Steps to reproduce

1. load or create terra world
2. build nether portal
3. try to enter

### Expected behavior
nether should load

### Actual behavior
game is laggy for short time, not entering the nether (same with end)

### Full stacktrace
No stack trace created

**Comment by ZEROOblivious** [comment]
Bukkit.yml? Was this added? 

worlds:
  World_nether:
    generator: Terra:NETHER 
    World_the_end:
     generator: Terra:BETTEREND

   Terra doesn't have a fully functioning End Dimension, End will be basic unless you built a fork of it. 
   Better-End doesn't work on 1.17.1 & is not added officially into Terra.

**Comment by Kloenk** [comment]
I don't have that config file on my fabric server.

(I also build Terra from source (latest master), but that did not start at all)

**Comment by ZEROOblivious** [comment]
https://github.com/PolyhedralDev/Terra/wiki/Quick-Start-Guide-for-Fabric#setting-up-a-world-on-a-fabric-server

Read up on the Fabric Side of Terra, my fault. 
Scroll down to the Fabric Server Section. 

Also Optifine is in Disabled State in your mod list.
