### ISSUE TITLE
Issues with Ice and Fire and Potentially More

### ISSUE THREAD

**Issue by Weberton01** [PolyhedralDev/Terra#241]
## Describe the issue

There appears to be a conflict issue with structure generation from the Ice and Fire mod and the Terra world generator. After starting a new world using the Terra world generator, I found no Ice and Fire structures or mobs. There are, however, structures and mobs from the Greek Fantasy mod, so this may be an issue on my side, but I wanted to check anyway. Also, there are no villagers spawning in the villages.

**Comment by dfsek** [comment]
Use the mod compatibility options implemented in #191
