### ISSUE TITLE
[Feature] [1.17] Terra stalactites/stalagmites should use pointed dripstone

### ISSUE THREAD

**Issue by tactlessfish** [PolyhedralDev/Terra#242]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that should be implemented by a pack or addon.

## Feature Description

In 1.17, Terra's stalactites and stalagmites should use vanilla pointed dripstone instead of walls and iron bars.

### What Problem Does This Solve?

It feels strange to see stalactites and stalagmites made out of walls and iron bars when pointed dripstone has been added to the game.

### A Solution You'd Like

Replace walls and iron bars with pointed dripstone. Additionally, add dripstone blocks around them to help them blend in.

### Alternative Solutions

1. Replace only walls and iron bars with pointed dripstone, without adding dripstone blocks around them.

**Comment by solonovamax** [comment]
@dfsek I don't have perms to transfer to the default pack repo
