### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by i-can-not-program** [PolyhedralDev/Terra#250]
## Describe the issue

OS is Manjaro Linux
I am using Java 16
If I clone the repository then run "./gradlew build" it gives this error:
<pre>
> Task :platforms:sponge:generateMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':platforms:sponge:generateMetadata' (type 'GenerateMetadata').
  - Type 'org.spongepowered.gradle.meta.GenerateMetadata' property 'mergeMetadata' has redundant getters: 'getMergeMetadata()' and 'isMergeMetadata()'.

    Reason: Boolean property 'mergeMetadata' has both an `is` and a `get` getter.

    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#redundant_getters for more details about this problem.
  - Type 'org.spongepowered.gradle.meta.GenerateMetadata' property 'mergeMetadata' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'org.spongepowered.gradle.meta.GenerateMetadata' property 'metadata' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'org.spongepowered.gradle.meta.GenerateMetadata' property 'metadataFiles' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'org.spongepowered.gradle.meta.GenerateMetadata' property 'provider' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
</pre>
I would prefer to compile it myself instead of downloading the mod.

**Comment by solonovamax** [comment]
Hmmmm.

Let me look at this, real quick.

**Comment by solonovamax** [comment]
Apply this patch to avoid compiling the sponge project:
```diff
 settings.gradle.kts | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/settings.gradle.kts b/settings.gradle.kts
index 8cd013d8..2c8de1d2 100644
--- a/settings.gradle.kts
+++ b/settings.gradle.kts
@@ -11,9 +11,9 @@ rootProject.name = "Terra"
 include("common")
 include("platforms:bukkit")
 include("platforms:fabric")
 include("platforms:region")
-include("platforms:sponge")
+// include("platforms:sponge")
 include("platforms:forge")

 pluginManagement {
     repositories {
```
