### ISSUE TITLE
Export command should include entities & NBT data

### ISSUE THREAD

**Issue by kacperleague9** [PolyhedralDev/Terra#262]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [ ] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 5.4.1
| Platform / Platform Version  | Purpur
| Any External Plugins or Mods | Oraxen
| Terra Packs In Use           | Default
| Terra Addons In Use          | None

## Issue Description

When using worldedit wand and trying to save structure with /terra structure export <name> the item frames don't save.

### Steps to reproduce

1. Make a worldedit selection of structure with item frames
2. Run /terra structure export <name> command
3. Check the generated file, it doesnt contain any info about item frame.

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

There isn't anything printing in the console, the command just runs fine.

</details>

### Additional details

By the way maybe it matters, my item frames are invisible.

Image of original structure:
![obraz](https://user-images.githubusercontent.com/34658474/131259701-545fdd0d-dbac-4449-acc5-9f4c09094d72.png)
Red wool is where i used wand

After exporting:
![obraz](https://user-images.githubusercontent.com/34658474/131259789-53a9aeb3-aeec-4daa-b092-4ad3350dc58b.png)

I guess you could just save info about the item frame.

**Comment by solonovamax** [comment]
item frames probably use nbt data, so this is a certified bukkit moment

**Comment by dfsek** [comment]
Item frames are entities. We should have the export command insert `entity` functions in the exported scripts, as well as store block & entity NBT data

of course, the latter would not be available on Bukkit

**Comment by kacperleague9** [comment]
I've seen it in some custom structure plugins

**Comment by solonovamax** [comment]
@kacperleague9 the problem is, we want to avoid any NMS usage for bukkit because, well, bukkit.

**Comment by solonovamax** [comment]
Well, we want to avoid NMS in the main plugin as much as possible. Because NMS is bad for a variety of reasons. So, the NMS addon is ""not officially supported"", even though it's also by us.
The reason being, NMS can be hard to support. Also, I'm pretty sure the NMS addon throw exceptions lol

**Comment by dfsek** [comment]
export command no longer exists. For static structures like that, use the Sponge Schematic addon.
