### ISSUE TITLE
[Bug/Proposition] Normalize pipeline sampler coordinates to match world coordinates

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#264]
Currently, the value of `pack:biomes.resolution`increases the final scale of the output of the biome provider. I believe that this shouldn't be the case, as the options main use case is for tuning performance (sacrificing fidelity to reduce biome calculations per unit of space), and shouldn't have an impact on increasing the scale of biomes.

The advantage of removing `pack:biomes.resolution`'s modification of scale is that you will be able to tune performance (via the reduced fidelity that comes with increasing the resolution) independently from other more suitable methods of scaling biome distribution.

For config developers who wish to maintain a 'baseline scale' any time resolution is changed, this would remove the process of reconfiguring the biome provider scale options. In addition, this would remove an additional factor that goes into biome scale, reducing unneeded complexity from the process of both understanding, and tuning biome scale.

**Comment by MaxBr5** [comment]
Glitchy generation is normally good!

**Comment by Astrashh** [comment]
Expanding on this, expander stages shouldn't affect sampler input coordinates either

Making this change will allow for other sampler usages to match biome distribution, allowing for things like adjusting terrain height based on proximity to oceans and or rivers

**Comment by Astrashh** [comment]
Test pack for this issue:
[264.zip](https://github.com/PolyhedralDev/Terra/files/9240208/264.zip)

**Comment by duplexsystem** [comment]
![Image](https://user-images.githubusercontent.com/25417900/183028031-7fa2e78c-e8b6-4652-8905-6fd02fd4c6f2.png)

**Comment by Astrashh** [comment]
Fixed with #355
