### ISSUE TITLE
[Feature] Beardification support for injected structures

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#265]
Add support for terrain 'globs' (dubbed 'beardification' by mojang) to generate under injected structures that are listed under `StructureFeature.NOISE_AFFECTING_FEATURES` (mojmap). 

###### Fabric 1.17.1 Terra 5.4.1 with `vanilla.structures` enabled

![image](https://user-images.githubusercontent.com/73215501/132616467-a38c8b36-9307-45a1-b8f5-8e8481446cb8.png)

###### Terrain 'Globs' under a village house from beardification (provided by @TelepathicGrunt)

![image](https://user-images.githubusercontent.com/73215501/132616751-76e1be79-7bf1-44f8-b0dd-8e765df04952.png)

**Comment by Astrashh** [comment]
For an implementation that uses the same technique as vanilla, we would have to split fetching noise from the `Sampler`, and palette application into two distinct stages within the generator, then sandwich injected structure generation between them, in order for the terrain to blend. This could lend itself to working with #92 too.

For a more approximate approach we could make the terrain globs independent of noise, which would allow structure population to be placed in the population order arbitrarily.

**Comment by dfsek** [comment]
implemented in 069b0d425a67f5004dab13d909b6f572293b90e5
