### ISSUE TITLE
[Feature] Image pipeline mutator

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#266]
Works similarly to the `REPLACE` mutator, but instead of a noise function, it would accept an image, working the same as the `IMAGE` biome provider.

**Comment by dfsek** [comment]
I feel like this would be better as a source rather than a mutator.

**Comment by Astrashh** [comment]
Implemented as a source  via the `pipeline-image` addon <https://terra.polydev.org/config/documentation/image/pipeline-image-source.html>
