### ISSUE TITLE
[Feature] Image biome provider tiling modes

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#267]
Add support for different tiling `mode`s, such as `TILED`, `SINGLE`, etc.. 
For the `SINGLE`, an additional biome would need to be specified for areas outside the initial image area.

**Comment by solonovamax** [comment]
Idea: what if we removed the biome providers all together and focused everything on the pipeline?
Then, you just add a way to derive "noise" from an image and integrate it into the pipeline.
Tiling can be done there.

**Comment by Astrashh** [comment]
Implemented via `pipeline-image` addon <https://terra.polydev.org/config/documentation/image/index.html>
