### ISSUE TITLE
[Feature] Option to use vanilla biome rather than registered Terra biome 

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#268]
###### DESCRIPTION

For Fabric specifically - the feature would involve having the option to set the biome (as seen in f3) to the one specified in the `biome:vanilla` key rather than one that has been registered by Terra through Fabric.

There would be two separate methods of setting this:

- Global - A boolean in `pack.yml`.

- Per biome - A boolean in biome configs for being able to set it on a per biome basis.

###### USE CASE

The main use of this would be for being able to generate worlds where only vanilla biomes may be required. There may be many reasons why this might be the case, such as pregenerating and using the world for other contexts outside of where Terra might be installed, or for solving niche compatibility issues (this should not be the go-to solution though).

**Comment by dfsek** [comment]
implemented in f7d53c9db33d64f1f2fa8cc4e8d4788b0783f7f3
