### ISSUE TITLE
Game crashes when trying to load into a previously made world

### ISSUE THREAD

**Issue by NotAMonke** [PolyhedralDev/Terra#271]
When I first played with this mod installed, I was able to create a world and play like normal. The issue came up when I quit the game and tried to load up the world again later. Instead of logging into the world, my game crashed. This happened every time I tested it. I'm not sure if it was because this mod was incompatible with some of the others I was using, but once I removed this mod, the issue stopped persisting. Here are some of the other mods I was playing with:
-YUNG's API along with better mineshafts, strongholds, and dungeons
-Additional Additions
-Charm
-Sodium
-Cloth Config

**Comment by solonovamax** [comment]
Please use the template for an issue.
