### ISSUE TITLE
[Bug] Empty/Dead Areas

### ISSUE THREAD

**Issue by RigidOfficial** [PolyhedralDev/Terra#277]
## Pre-Issue Checklist

- [X] I have checked that I am on the latest version of Terra.
- [X] I have searched the github issue tracker for similar issues, including closed ones.
- [X] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [X] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [ ] I have attached a copy of the `latest.log` file - **I have not been able to reproduce this, and did not keep the original log file**.
- [X] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | Terra-bukkit-5.4.1-BETA+efd1665c-shaded
| Platform / Platform Version  | Paper 1.17.1 @ [#381](https://github.com/PaperMC/Paper/commit/db0bff9c6ad42eefa22b094bb92df9bf3bc8ec66) (2021-11-13)
| Any External Plugins or Mods | ActionHealth, Brewery, DropHeads, Graves, GSit, ImageMaps, LPC, LuckPerms, PlaceholderAPI, ProtocolLib, SetHomes, Terra, TwoPlayerHorseRiding, voicechat
| Terra Packs In Use           | DEFAULT v2.0.0
| Terra Addons In Use          | Terra-Bukkit v1.0.0

## Issue Description

Sometimes when generating terrain, a region of chunks will not be populated with ores, plants or trees.

### Steps to reproduce

**I've been unable to reproduce this in even quite similar conditions.**

1. Playing on server with around 10 people on, all exploring.
2. Server is on around 11tps.
3. People discover chunks which don't have anything spawned

### Expected behavior

Chunks should generate populated by ores, plants, and trees.

### Actual behavior

Chunks instead generate completely empty, only the ground generates, with all of its patterns, but without grass, without anything.

![image](https://user-images.githubusercontent.com/94168811/142195289-a26d5c09-713e-49b2-a617-9ee9a7d68dab.png)
*See red area, "dead chunks".*

![2021-11-17_14 57 32](https://user-images.githubusercontent.com/94168811/142195515-6a353c47-2543-4031-8b57-155f0acbfafd.png)
*Image of what this looks like, terrain features like sand slabs still generate.*

### Additional details

Seed: 3562953716345550468
Location: -2150 -710

**Comment by dfsek** [comment]
[don't use `/reload`](https://madelinemiller.dev/blog/problem-with-reload/)
