### ISSUE TITLE
[Bug] Chunk regeneration with Paper do default world regeneration

### ISSUE THREAD

**Issue by supermem99** [PolyhedralDev/Terra#301]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name  regeneration don't work with paper api                   | Value |
|------------------------------|-------|
| Terra Version : Terra-bukkit-6.0.0-BETA+0f767c689 | Terra-bukkit-6.0.0-BETA+0f767c689
| Platform / Platform Version:  Paper 1.18.1 #7425 | Paper 1.18.1 #7425
| Any External Plugins or Mods: No, its still without external plugins, but "Lands" has the regenerate command  | No, its still without external plugins, but "Lands" has the regenerate command
| Terra Packs In Use:   | Overworld@0.1.0
| Terra Addons In Use: a list of the default packs (cleaninstall with this terra version) | a list of the default packs (cleaninstall with this terra version) 

## Issue Description

'When regenerating a chunk with lands (which use paperapi regenerator), the chunk will be like a default terrain world generator

### Steps to reproduce

i claim the chunk 
and after unclaiming the chunk should be regenerate as it was before
but it will be a default worldgenerator chunk
(multiverse world has the terra generator configured)

### Expected behavior

It should be regenerated like the terra chunk generator

### Full stacktrace

<details>
<summary>Worldgeneration of Terra doesnt  work with paper api feature regeneration</summary>

<!--
No errors

</details>

**Comment by dfsek** [comment]
You've babbled about this several times and I still have no idea what this means. Can you please explain the issue, in more detail? What are you trying to do?

**Comment by dfsek** [comment]
Submit this issue to Paper, that method should be getting the custom generator we define. Somewhere in their implementation the method is erroneously getting the default chunk generator instead of the custom one.

**Comment by solonovamax** [comment]
The method for chunk regeneration (which is the only reference I could find to regeneration of chunks), is [deprecated in the paper api](https://papermc.io/javadocs/paper/1.18/org/bukkit/World.html#regenerateChunk(int,int)).

Further, this method is on a *bukkit* class, indicating that it is not a paper feature but a bukkit one.

Using a simple search, I have found references to it as far back as 2018 (I didn't search for long)

This is a deprecated method which is stated to not work. Open an issue with bukkit if you want this fixed, but do not expect them to fix it.

**Comment by solonovamax** [comment]
The method for chunk regeneration (which is the only reference I could find to regeneration of chunks), is [deprecated in the paper api](https://papermc.io/javadocs/paper/1.18/org/bukkit/World.html#regenerateChunk(int,int)).

Further, this method is on a *bukkit* class, indicating that it is not a paper feature but a bukkit one.

Using a simple search, I have found references to it as far back as 2018 (I didn't search for long)

This is a deprecated method which is stated to not work. Open an issue with bukkit if you want this fixed, but do not expect them to fix it.

**Comment by Roan-V** [comment]
@solonovamax https://github.com/PaperMC/Paper/pull/7425
