### ISSUE TITLE
[Feature] Chunk regeneration

### ISSUE THREAD

**Issue by supermem99** [PolyhedralDev/Terra#302]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that should be implemented by a pack or addon.

A Feature command, which makes it possible to regenerate a specific chunk. Like /chunkregen x y world. But the commandbuilding can be how you like.

Because of a research its better to implement a own feature for terra because of incompatibility or other issues.

### What Problem Does This Solve?

When you or your user did some bulding mistakes or griefing on terra world, its annoying to create a new world. Moreover its a advantage for all users for something like claimplugins. You can easily restore the chunk back.

I will be very happy and i think terra will be more popular for survival games.

### A Solution You'd Like

A command or a api event or something like that for regeneration.

### Alternative Solutions

1. Maybe a api inplement

### Additonal Context

It will be a little more work but worth it.

**Comment by dfsek** [comment]
This is out of the scope of Terra. Use WorldEdit, or create a simple plugin using Bukkit's regeneration API.
