### ISSUE TITLE
[Feature] Improved trees should grow from saplings

### ISSUE THREAD

**Issue by LuciusofLegend** [PolyhedralDev/Terra#322]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description

I would like Terra trees to spawn from saplings based on biome.

### What Problem Does This Solve?

When I destroy trees and replant them, they do not grow to be as interesting as the trees I find while exploring.

### A Solution You'd Like

If possible, it would be great if saplings grow into upgraded trees based on their type and biome.

### Alternative Solutions

I do not really have alternatives :/

**Comment by Kaisarion** [comment]
@duplexsystem is this officially implemented in Terra now? It does not seem to be functional

**Comment by duplexsystem** [comment]
It is implemented by not released
