### ISSUE TITLE
Server Shutdown

### ISSUE THREAD

**Issue by ArastaD0t** [PolyhedralDev/Terra#349]
## Server Stoping
After world start loading server exit 

[Log](https://pastebin.com/U8sGw6BD)

**Comment by Roan-V** [comment]
Please use the discord for support questions.
These issues are for actual bugs/issues within the plugin.

Anyway you should use paper instead of spigot.
https://papermc.io
All spigot plugins will keep working perfectly fine, but your server will perform better
Terra also requires paper to run

**Comment by ArastaD0t** [comment]
Thank

Dne ne 17. čvc 2022 18:38 uživatel Roan-V ***@***.***> napsal:
