### ISSUE TITLE
No fences in trees

### ISSUE THREAD

**Issue by Cyliann** [PolyhedralDev/Terra#35]
Any idea how can I configure pack, so trees would be without fences? I briefly read wiki, but I couldn't find it anywhere.

**Comment by dfsek** [comment]
Load tree structures, remove fences, export tree structures.
https://github.com/PolyhedralDev/Terra/wiki/Tree-Configuration
https://github.com/PolyhedralDev/Terra/wiki/Working-With-Structures

**Comment by Cyliann** [comment]
Thanks a lot
