### ISSUE TITLE
[Feature] Sneakier biomes.  Nesting inside the default minecraft world!

### ISSUE THREAD

**Issue by LuciusofLegend** [PolyhedralDev/Terra#360]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description

The ability to define the 'type' or 'group' of a biome.

### What Problem Does This Solve?

I recently noticed that Terra is incompatible with Charmonium.  You can use them together, but Charmonuim's biome specific ambiance didn't have the same biomes to work with.  Also, slimes do not spawn except in slime chunks.

### A Solution You'd Like

I propose a solution to the two problems above (and others as well).  All we have to do is:  When adding a new biome, you may (but aren't required to) add a parent biome as an argument.  The parent has to be a default Minecraft biome.  This way, things like Charmonuim keep their compatibility, but if you wanted to make an alien landscape that didn't fit with any of the default areas, you could omit the parent argument.

I would really love this, it would make Terra so much more compatible.  Not only with mods like Charmonium, but structure mods and creature mods too!

**Comment by LuciusofLegend** [comment]
I should have stated this in the beginning, I certainly wouldn't blame you for not implementing this feature because it requires other mods to also participate in the changes, which isn't practical.  I'm going to make a separate issue about the slimes in the default config repo.  Let me know if that's a bad idea.

**Comment by duplexsystem** [comment]
As of Terra 6.2.0 all of this is achievable via config, in fact this exact feature is already implemented in 6.2.0, however it will be removed from the 7.0.0 release in favor of manually defining all biome modifiers

**Comment by LuciusofLegend** [comment]
Oh, I apologize for the invalid issue.

**Comment by duplexsystem** [comment]
Better documentation on these features will come with 7.0.0

**Comment by LuciusofLegend** [comment]
Ok.
