### ISSUE TITLE
[Feature] Adding support to ItemsAdder

### ISSUE THREAD

**Issue by RareMaker50** [PolyhedralDev/Terra#361]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description
Adding support for ItemsAdder ores into Terra Worlds

### What Problem Does This Solve?
When I try to add custom ores into my world using terra generator/world, It realy annoys me that I have to either manually place the ores or have to use world edit to add the ores and even those solutions aren't that great/work well.

### A Solution You'd Like
Being able to add itemsadder:<ore_name> to the world files so the ores would be automatically generated there like on other inferior generators

### Alternative Solutions
1. Manually replacing, takes too much time and isn't efficient for an entire world
2. Using world edit to replaceall, to resource heavy and doesn't even work well/work at all sometimes

1. 
3. 
4.

**Comment by Sancires** [comment]
This is something that would be added by an addon and not included within Terra itself.
