### ISSUE TITLE
Cannot regen terrain using world edit

### ISSUE THREAD

**Issue by solonovamax** [PolyhedralDev/Terra#37]
When running //regen with world edit on a bit of terrain, it errors because `getDefaultWorldGenerator` is not run.
We should stop relying on this method and move that code elsewhere.
(I can't find the old stack trace and am lazy, but there was an NPE at `TerraWorld` line 34.)

Honestly, the whole `WorldConfig` class should be completely redone, as there is no reason to store the image in memory once it's loaded and you've built an array of the biomes.

**Comment by dfsek** [comment]
This has been fixed, and WorldConfig is no more.
