### ISSUE TITLE
[Feature / Bug] Implement beardification on Bukkit

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#370]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including
  closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  
- [ ] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Issue Description

Beardification is not currently implemented on the Bukkit implementation, which causes ancient cities and other potential underground structures to be buried, as well as partially floating structures on cliffs (such as village houses).

Image of buried ancient city provided by discord user `MagmaSlime_123#4333`:
![image](https://user-images.githubusercontent.com/73215501/188345108-e16f5239-9c4a-4874-8eec-3129423896f7.png)

**Comment by MagmaBro123** [comment]
Thank you.
