### ISSUE TITLE
A 1.19 version of Terra being wrongly considered as"latest Terra version for 1.18"

### ISSUE THREAD

**Issue by ZZZank** [PolyhedralDev/Terra#384]
## Describe the issue
In the versions section of the official document, the latest Terra version of 1.18 Fabric is 6.1.1, but it is actually version 1.19, and the latest version of 1.18 in Modrinth is 6.0.0.
在官方文档的versions部分，1.18 Fabric的最新Terra版本被标记为6.1.1，但它实际上是1.19的版本，Modrinth中1.18的最新版本是6.0.0

**Comment by pumken** [comment]
This is true; 6.1.1-BETA is indeed incompatible with Fabric 1.18.2 and requires 1.19.x. This is an issue with TerraDocs, I think.
