### ISSUE TITLE
[Bug] Sponge schematics don't use offset field during placement

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#394]
See the 'offset' field in the spec <https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-3.md#fields> for intended behaviour.

**Comment by amnithyst** [comment]
Is there any update when this bug is going to be fixed? Have been noticing it too!

**Comment by Astrashh** [comment]
Fixed in 1b5095dd363aefc80990a79eefdc131a4658a93e..73e0899e7ca4da2b7081de9ab3da36ca1ce6bdd7 slated for v6.3.0. This will not apply to Sponge v2 schematics not exported by WorldEdit, as relative offset handling in the v2 spec is ambiguous. The v3 spec defines this more concretely.
