### ISSUE TITLE
[Feature] 1.20 compatibility

### ISSUE THREAD

**Issue by AlexanderMoebius** [PolyhedralDev/Terra#404]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description

Terra should be compatible with the current 1.20.1

### What Problem Does This Solve?

Terra could be used on current generation servers.

### A Solution You'd Like

Update of Terra to run in 1.20.1

**Comment by Astrashh** [comment]
Development is done on <https://github.com/PolyhedralDev/Terra/tree/dev/1.20.1>, merging of this branch is pending on https://github.com/PolyhedralDev/TerraOverworldConfig/pull/149 being finished and merged.

**Comment by AlexanderMoebius** [comment]
Oh, thanks for the information!

It would be great if you could bring a release to spigot :)
