### ISSUE TITLE
[Feature] <Put your title here>When will update 1.20.1, please

### ISSUE THREAD

**Issue by xiaofengv233** [PolyhedralDev/Terra#405]
When will update 1.20.1, please

**Comment by ONdraid** [comment]
Hi @xiaofengv233,

The developers are currently working on it and expect it to be released within a month.

However, I would like to kindly remind you that GitHub issues are primarily for reporting bugs and discussing feature requests. For general questions and discussions, please use the Discord server (https://discord.gg/PXUEbbF).

**Comment by solonovamax** [comment]
Closing issue.
- Didn't follow template
- you should ask for ETAs in the discord. but, don't necessarily expect super accurate ones.
