### ISSUE TITLE
[Feature] Bukkit 1.20.2 NMS

### ISSUE THREAD

**Issue by ryzech** [PolyhedralDev/Terra#416]
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description

Currently, the latest versions and even the dev/6.4.0 branch, do not implement NMS bindings for v1_20_R2. I'm unsure as to whether or not this actually causes an issue, but it does present an error/warning on startup and it would be nice for that to not appear. Though I know this will take a bit, so no rush at all.

### What Problem Does This Solve?

On startup it presents an error saying 'NMS bindings for version do not exist. Support for this version is limited'. It would be preferable for it to not have that error, for peace of mind and potential issues that may occur.

### A Solution You'd Like

Re-implement the 1.20.1 bindings but update them for the NMS changes in the 1.20.2 update from Bukkit.

### Alternative Solutions

1. If the plugin works as normal, could potentially just remove the warning if it's version 1.20.2. Though this wouldn't be the best option, it is an alternative that exists.

**Comment by duplexsystem** [comment]
https://github.com/PolyhedralDev/Terra/tree/dev/1.20.2

We are waiting for a couple of things before merging

**Comment by ryzech** [comment]
Ah i see, missed that branch somehow
