### ISSUE TITLE
Don't log old addon deprecations by default

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#418]
Example: https://github.com/PolyhedralDev/Terra/blob/b3f80dcb648ecf7367a4120472aaf6b0a1b921a1/common/addons/biome-provider-image/src/main/java/com/dfsek/terra/addons/biome/image/ImageBiomeProviderAddon.java#L53

The `debug.log` plugin/mod config option would probably be the option that enables these messages

**Comment by pumken** [comment]
Correct me if I'm wrong, but this seems to be completed already with commit e80e998.

**Comment by duplexsystem** [comment]
That is correct.

**Comment by duplexsystem** [comment]
> Correct me if I'm wrong, but this seems to be completed already with commit [e80e998](https://github.com/PolyhedralDev/Terra/commit/e80e998cec9d41f5509b60605b8ae5134af6bae6).

Are you on our discord or matrix?

**Comment by pumken** [comment]
Discord; username pumk3n.
