### ISSUE TITLE
Support Minecraft 1.21

### ISSUE THREAD

**Issue by rainbowsource** [PolyhedralDev/Terra#462]
I updated the server to 1.21, but terra is not supporting it.

**Comment by MeoNguOfficial** [comment]
Update now!!! Please

**Comment by PapiCapi** [comment]
You can compile it yourself from this PR https://github.com/PolyhedralDev/Terra/pull/461

**Comment by JanReich** [comment]
We have issues with compiling this pull request this there a place where we can download the jar?

**Comment by kylemarham** [comment]
+1

**Comment by OpenEdgeLines** [comment]
+1

**Comment by Little100** [comment]
+1
