### ISSUE TITLE
Ores and stone on beaches

### ISSUE THREAD

**Issue by Mayzone** [PolyhedralDev/Terra#465]
[mods.txt](https://github.com/user-attachments/files/16316871/new.1.txt)
## Describe the issue
https://www.swisstransfer.com/d/456098cd-bb1c-4e2d-8d71-f0a780bfe89e
Beaches look bad, ores and stone spawn in around over the sand and sometimes stone spawn over grass. i'm on 1.19.2 forge. I have some structure mods but i assume they just flatten where they spawn and wont affect world gen.

**Comment by solonovamax** [comment]
1. Please follow the bug report issue template.
2. Open the issue on PolyhedralDev/TerraOverworldConfig, as this is relevant to the config in use, not Terra.
3. 1.19.2 forge is no longer supported.
