### ISSUE TITLE
Domain distortion option for noise configuration

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#51]
The ability to distort noise by putting input coordinates of a noise generator through another defined noise generator - along the lines of this https://www.iquilezles.org/www/articles/warp/warp.htm
This should also be nest-able, so you can distort the noise that's distorting noise, dawg

**Comment by dfsek** [comment]
Implemented in 346a8826aaecc423c48ba0d2bde293fad1444991
