### ISSUE TITLE
Distance to edge return option for cellular noise

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#56]
Having the option to use noise like the image below as an extension of the current cellular return options would be nice for things like palettes, where you could could have 'cracked' looking grounds, or whatever else people come up with. You can get kinda similar results with the current distance return, but the issue is that centers of cells look very circular

Distance to edge example:
![image](https://user-images.githubusercontent.com/73215501/104718323-d1114d80-577e-11eb-8993-f78ce46c9542.png)

This page has an example implementation https://www.ronja-tutorials.com/2018/09/29/voronoi-noise.html 
![image](https://user-images.githubusercontent.com/73215501/104718620-42e99700-577f-11eb-9634-c9ea0abbd6a9.png)

**Comment by dfsek** [comment]
This is already an option, with the `cellular.return` key in noise configs.

**Comment by Astrashh** [comment]
The current distance option calculates distance from the cell center - which gives different results compared to distance from center - unless I'm missing an option for it

Comparison:


Center distance (inverted for comparison)
![Screenshot_20210116-024410_Firefox.jpg](https://user-images.githubusercontent.com/73215501/104747758-fe70f200-57a4-11eb-9460-2d32fa87c884.jpg)

Edge distance
![Screenshot_20210116-024530_Firefox.jpg](https://user-images.githubusercontent.com/73215501/104747803-0d57a480-57a5-11eb-996f-8881377d9051.jpg)

**Comment by dfsek** [comment]
`Distance2Sub` return type is what you're looking for. There are many variations of the `Distance2` return type:
* `Distance2Add`
* `Distance2Sub`
* `Distance2Mul`
* `Distance2Div`

`Distance2Sub`:
![image](https://user-images.githubusercontent.com/39248502/104749787-74774980-5710-11eb-9b48-2d02c2bfccc4.png)
