### ISSUE TITLE
Terrascript - Get structure rotation relative to world function

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#60]
Similar to getOriginX - Y - Z() functions, but would return the rotation of a structure relative to the world.

**Comment by solonovamax** [comment]
what would you need that for?

**Comment by dfsek** [comment]
Added `rotation` and `rotationDegrees` for getting rotation as either a `str` representing the enum constant, or as a `num` representing its value in degrees. Added in 25acda44107e20430c1f68ed1bfef03b84fbb1bc
