### ISSUE TITLE
Terrascript - Smart waterlog

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#62]
Would be nice to be able to set an option within terrascript scripts that adds the waterlogged blockstate to any block() function if the x, y, z returns "OCEAN" with the check() function

This is possible to implement by hand but would be very time consuming - especially if you have a large amount of scripts that run into this issue:
![image](https://user-images.githubusercontent.com/73215501/105575311-d4c85400-5dbe-11eb-828c-9355dd0faccc.png)

**Comment by solonovamax** [comment]
Might be interesting to have a function like `enableWaterLogging()`, and then all future blocks placed in water will be waterlogged, then `disableWaterLogging()` to stop it.
Alternatively, we could just do `waterLogging(true)` and `waterLogging(false)`.

**Comment by dfsek** [comment]
Implemented as `setWatelog(bool)` in 5028582198407694b8e75a9e66edc7efde49a1dd
