### ISSUE TITLE
Double cant be converted to string

### ISSUE THREAD

**Issue by Xogue** [PolyhedralDev/Terra#65]
inside a custom config pack.yml, the "version" option cannot be a "double"

version: 0.1 -- Doesn't work, as a double cannot apparently be cast into a string. (at least it didnt work for me. I didnt do any extra testing)
version: 0.1.0 -- Does work. not seen as a double.

**Comment by dfsek** [comment]
If you want a string value, surround it with quote marks.

[YAML Syntax](https://en.wikipedia.org/wiki/YAML#Syntax)
