### ISSUE TITLE
how to add custom structures?

### ISSUE THREAD

**Issue by JeffsHer** [PolyhedralDev/Terra#7]
i dont know how to make .structure files i tried searching it and it just showed me structure blocks

**Comment by JeffsHer** [comment]
help

**Comment by dfsek** [comment]
Issues are for bug reports/feature requests, not receiving help. If you need help, join the Discord. See the [Working with Structures](https://github.com/PolyhedralDev/TerraDefaultConfig/wiki/Working-With-Structures) page of the Wiki.
