### ISSUE TITLE
Purpur Chunk Generation Error

### ISSUE THREAD

**Issue by OskarZyg** [PolyhedralDev/Terra#71]
I haven't tested anywhere else, but purpur appears to have errors and shut the server down for no reason, (the mod worked previously, it just broke now)

Log:
https://paste.gg/p/anonymous/87e00ab165504c78a1ed69aaca5e36f9

Configs:
https://paste.gg/p/anonymous/5ed5b8db6a434ec6a64ca01abbe14414

**Comment by dfsek** [comment]
Test on other Paper forks, unable to replicate on Paper or Purpur.

**Comment by OskarZyg** [comment]
Removed All other plugins of mine, no error. Seems like a plugin issue for now.

**Comment by dfsek** [comment]
Why did you close this... If it's a plugin issue, figure out what plugin it is and report back.

**Comment by OskarZyg** [comment]
Sorry for closing this (misclick while alt-tabbing), I have no idea how, but I removed all plugins and added one by one, and I've added them all back, and am unable to reproduce. Exact same configs, etc. I have 0 idea what the culprit is.

**Comment by solonovamax** [comment]
This seems like an issue to do with the server software itself. Be it paper, purpur, tuinity, or bukkit. Because I don't see why another plugin would be able to do anything that would cause a concurrent modification error to arise from *our plugin*.
It might just be so unbelievably rare that we never found it before now. Who knows.

**Comment by OskarZyg** [comment]
What does a concurrent modification error mean necessarily? I might be able to get the cause if I know what I'm looking for.

**Comment by solonovamax** [comment]
Basically, it means that a thread that is not the main thread attempted to modify the chunk data. Which is illegal, because chunk data can only be modified by 1 thread at a time (so only the main thread can modify it.)

What were you doing when it occurred?

**Comment by OskarZyg** [comment]
I wasn't doing anything at the time, I just started the server and it crashed a few times, any idea if it could be the somewhat redundant (in this case) [AntiSeedCracker](https://www.spigotmc.org/resources/antiseedcracker-1-15-1-16-x.81495/)?

**Comment by dfsek** [comment]
I'm going to close this since I have been unable to replicate this with extensive testing on Paper and Purpur. If you can provide steps to replicate, please reopen.
