### ISSUE TITLE
Config schema versions to maintain cross version parity for packs

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#79]
The option to provide a 'Schema version' (there's probably a better name) for Terra packs, such that in the event of an update changing the way things are configured, a warning will be thrown if the pack's schema version does not match the plugin's schema version. This will allow for packs to maintain parity between old and new versions, and notify people in the case that a pack hasn't been updated to match any changes to the way things are configured.

**Comment by dfsek** [comment]
Implemented with 6.0's version dependencies
