### ISSUE TITLE
Incompatibility with Slight GUI Modifications (Fabric)

### ISSUE THREAD

**Issue by Toseflo** [PolyhedralDev/Terra#82]
When trying to load the Fabric Version of Terra with Slight GUI Modifications (https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications), the game crashes before startup.
Error log:
[error log.txt](https://github.com/PolyhedralDev/Terra/files/6041965/error.log.txt)

**Comment by solonovamax** [comment]
Does it work without Terra?

Also, looking at the curseforge page, other people seem to be having this issue too with other mods.

**Comment by Toseflo** [comment]
Oh you are right. I created a new instance with most of my mods to test Terra and didn't notice that Slight GUI Modifications needs Cloth API to work. 
Works fine now with Cloth API installed.
