### ISSUE TITLE
Custom large oak tree "oak_leave" typo

### ISSUE THREAD

**Issue by AshenGaming** [PolyhedralDev/Terra#85]
I seem to have an issue with structures that I've exported using the `/te structure export` command.

I have 4 structures, as follows:

OAK_LARGE01: https://pastebin.com/trzzRxA3
OAK_LARGE02: https://pastebin.com/AgMsFQYW
OAK_LARGE03: https://pastebin.com/xvizfLMx
OAK_LARGE04: https://pastebin.com/sktYJt3c

These were schematics that I imported into the world, selected and set up signs for, and then exported with Terra. When loading these trees via the `/te structure load full <NAME> 0` command, they generate as expected.

However, when generating a new world with them *(using Multiverse) I get the stacktrace below.

https://pastebin.com/6QTU9FiA

The first one will generate in my world correctly, however, the other three do not. When any of the bottom three are included in my biome .yml file the server will crash upon generation with the stacktrace.

I have tried including the generator in the `bukkit.yml` and not including it, but it occurs in both instances.

*Versions*
Terra: `Terra-bukkit-4.3.0-BETA+6d51da31-shaded`
Tuinity: `tuinity-paperclip.jar build #192`
Multiverse: `Multiverse-Core-4.2.2`

**Comment by dfsek** [comment]
You probably did not properly define the tree in your structure configuration, causing it to generate the included oak tree, which has a typo:
https://github.com/PolyhedralDev/Terra/blob/master/common/src/main/java/com/dfsek/terra/api/world/tree/fractal/trees/OakTree.java#L42

**Comment by AshenGaming** [comment]
Ahh, I see, that may be the cause. I couldn't seem to find updated documentation on the new structure (assuming signs are still used?)

**Comment by dfsek** [comment]
Structure config: https://github.com/PolyhedralDev/Terra/wiki/Structure-Configuration

TerraScript:
* https://github.com/PolyhedralDev/Terra/wiki/TerraScript
* https://github.com/PolyhedralDev/Terra/wiki/TerraScript-Syntax
* https://github.com/PolyhedralDev/Terra/wiki/TerraScript-Functions

**Comment by AshenGaming** [comment]
Thank you - I'll update my files and see how I get on 👍

**Comment by dfsek** [comment]
Underlying issue fixed in c0d26256af8c8fc8c450d24afdcff4d41905c93a
