### ISSUE TITLE
Adventure integration for platform agnostic chat stuff 

### ISSUE THREAD

**Issue by dfsek** [PolyhedralDev/Terra#90]
In order to be able to handle chat in a platform-agnostic way (beyond just strings), implement [Adventure](https://github.com/KyoriPowered/adventure).

Adventure has [implementations](https://github.com/KyoriPowered/adventure-platform) for all platforms we plan to support. ([Fabric](https://github.com/KyoriPowered/adventure-platform-fabric), Bukkit, and Sponge. It would be unneeded in the region generator.)

Advantages:
* Allows us to style and add rich components to chat messages in a platform-agnostic setting
* Adventure is a popular API, already being implemented by Paper. It would be useful (and familiar) to addon developers.

Disadvantages:
* We would depend on Adventure's platform implementations' updates to release our own updates.

**Comment by solonovamax** [comment]
Adventure's api seems kinda ehhhh to me. Are there any alternatives?

Also, here's another alternative that we could use (which is how I was planning to do it in my command rewrite): format modifiers. You'd be able to include something like `%{grey}` in a message to make it grey, then it'd be processed by a platform-specific utility and either made grey or have it stripped out.
