### ISSUE TITLE
General repository maintenance.

### ISSUE THREAD

**Issue by solonovamax** [PolyhedralDev/Terra#93]
We should look at adding files such as `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md`, and `FUNDING.yml`, `.github/ISSUE_TEMPLATE/*` files, and `.github/PULL_REQUEST_TEMPLATE/*`.

It's pretty self-explanatory why these files would be good to have.

I'm currently looking at making PR and issue templates, (combining the good features from some already premade ones + adding some specifics for our project), but we'll need to go over them to make sure they fit our needs. I'll open a PR when I finish that.

**Comment by Huskydog9988** [comment]
To continue with the idea of repo maintenance, you might want to consider moving all ideas to the discussions thing. I haven't seen much use of it, but it seems to be a good concept so far.
