### ISSUE TITLE
Allow functions to be defined within expression samplers

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#95]
Similar to how expression samplers can already have their own variables and noise definitions, it would be helpful to allow math functions to be defined within expression samplers too. Perhaps to avoid confusion between noise definitions (which is under the `functions` key, it could be re-named to something like `noise-functions`.

**Comment by dfsek** [comment]
It'll probably be called `expressions`

**Comment by dfsek** [comment]
Implemented in b3868bd75072c4ddabaf97e812e7fddc6b701c5f
